name: isthmus_env_gpu
channels:
  - anaconda
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - alsa-lib=1.2.13=hb9d3cd8_0
  - asttokens=3.0.0=pyhd8ed1ab_1
  - attr=2.5.1=h166bdaf_1
  - blas=1.0=openblas
  - bottleneck=1.4.2=py39ha9d4c09_0
  - brotli=1.0.9=h5eee18b_8
  - brotli-bin=1.0.9=h5eee18b_8
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.2.25=h06a4308_0
  - cairo=1.18.0=h3faef2a_0
  - comm=0.2.2=pyhd8ed1ab_1
  - contourpy=1.2.0=py39hdb19cb5_0
  - cudatoolkit=10.1.243=h6bb024c_0
  - cudnn=7.6.5=cuda10.1_0
  - cupy=8.3.0=py39hcaf9a05_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - cython=3.0.11=py39h5eee18b_1
  - dbus=1.13.18=hb2f20db_0
  - debugpy=1.8.11=py39hf88036b_0
  - decorator=5.1.1=pyhd8ed1ab_1
  - exceptiongroup=1.2.2=pyhd8ed1ab_1
  - executing=2.1.0=pyhd8ed1ab_1
  - expat=2.6.4=h6a678d5_0
  - fastrlock=0.8.3=py39h5eee18b_0
  - font-ttf-dejavu-sans-mono=2.37=hd3eb1b0_0
  - font-ttf-inconsolata=2.001=hcb22688_0
  - font-ttf-source-code-pro=2.030=hd3eb1b0_0
  - font-ttf-ubuntu=0.83=h8b1ccd4_0
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-anaconda=1=h8fa9717_0
  - fonts-conda-ecosystem=1=hd3eb1b0_0
  - fonttools=4.51.0=py39h5eee18b_0
  - freetype=2.12.1=h4a9f257_0
  - gettext=0.22.5=he02047a_3
  - gettext-tools=0.22.5=he02047a_3
  - glib=2.80.2=hf974151_0
  - glib-tools=2.80.2=hb6ce0ca_0
  - graphite2=1.3.14=h295c915_1
  - gst-plugins-base=1.24.4=h9ad1361_0
  - gstreamer=1.24.4=haf2f30d_0
  - harfbuzz=8.5.0=hfac3d4d_0
  - icu=73.2=h59595ed_0
  - imageio=2.37.0=pyhfb79c49_0
  - importlib-metadata=8.5.0=pyha770c72_1
  - importlib_resources=6.4.0=py39h06a4308_0
  - iniconfig=1.1.1=pyhd3eb1b0_0
  - intel-openmp=2022.1.0=h9e868ea_3769
  - ipykernel=6.29.5=pyh3099207_0
  - ipython=8.18.1=pyh707e725_3
  - jedi=0.19.2=pyhd8ed1ab_1
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.7.2=pyh31011fe_1
  - kiwisolver=1.4.4=py39h6a678d5_0
  - krb5=1.21.3=h143b758_0
  - lame=3.100=h7b6447c_0
  - lazy-loader=0.4=pyhd8ed1ab_2
  - lazy_loader=0.4=pyhd8ed1ab_2
  - lcms2=2.16=hb7c19ff_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=4.0.0=h6a678d5_0
  - libasprintf=0.22.5=he8f35ee_3
  - libasprintf-devel=0.22.5=he8f35ee_3
  - libbrotlicommon=1.0.9=h5eee18b_8
  - libbrotlidec=1.0.9=h5eee18b_8
  - libbrotlienc=1.0.9=h5eee18b_8
  - libcap=2.71=h39aace5_0
  - libclang-cpp15=15.0.7=default_h127d8a8_5
  - libclang13=18.1.7=default_h087397f_0
  - libcups=2.3.3=h4637d8d_4
  - libdeflate=1.20=hd590300_0
  - libedit=3.1.20230828=h5eee18b_0
  - libevent=2.1.12=hdbd6064_1
  - libexpat=2.6.4=h5888daf_0
  - libffi=3.4.4=h6a678d5_1
  - libflac=1.4.3=h59595ed_0
  - libgcc=14.2.0=h77fa898_1
  - libgcc-ng=14.2.0=h69a702a_1
  - libgcrypt-lib=1.11.0=hb9d3cd8_2
  - libgettextpo=0.22.5=he02047a_3
  - libgettextpo-devel=0.22.5=he02047a_3
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libglib=2.80.2=hf974151_0
  - libgomp=14.2.0=h77fa898_1
  - libgpg-error=1.51=hbd13f7d_1
  - libiconv=1.17=hd590300_2
  - libjpeg-turbo=3.0.3=h5eee18b_0
  - libllvm11=11.1.0=h9e868ea_6
  - libllvm15=15.0.7=he89c38a_4
  - libllvm18=18.1.7=hb77312f_0
  - libogg=1.3.5=h27cfd23_1
  - libopenblas=0.3.21=h043d6bf_0
  - libopus=1.3.1=h5eee18b_1
  - libpng=1.6.43=h2797004_0
  - libpq=16.6=h035377e_1
  - libsndfile=1.2.2=hc60ed4a_1
  - libsodium=1.0.20=h4ab18f5_0
  - libsqlite=3.46.0=hde9e2c9_0
  - libstdcxx=14.2.0=hc0a3c3a_1
  - libstdcxx-ng=14.2.0=h4852527_1
  - libsystemd0=256.9=h2774228_0
  - libtiff=4.6.0=h1dd3fc0_3
  - libuuid=2.38.1=h0b41bf4_0
  - libvorbis=1.3.7=h7b6447c_0
  - libwebp-base=1.3.2=h5eee18b_1
  - libxcb=1.15=h7f8727e_0
  - libxkbcommon=1.7.0=h662e7e4_0
  - libxml2=2.13.5=hfdd30dd_0
  - libzlib=1.2.13=h4ab18f5_6
  - llvmlite=0.38.0=py39h4ff587b_0
  - lz4-c=1.9.4=h6a678d5_1
  - matplotlib=3.8.4=py39h06a4308_0
  - matplotlib-base=3.8.4=py39h1128e8f_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - mkl=2022.1.0=hc2b9512_224
  - mkl-service=2.4.0=py39hb699420_0
  - mkl_fft=1.3.1=py39h051f8f4_4
  - mkl_random=1.2.2=py39h8b66066_1
  - mpg123=1.32.9=hc50e24c_0
  - mysql-common=8.3.0=hf1915f5_4
  - mysql-libs=8.3.0=hca2cd23_4
  - nccl=2.8.3.1=hcaf9a05_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - nspr=4.35=h6a678d5_0
  - nss=3.100=hca3bf56_0
  - numba=0.55.1=py39h51133e4_0
  - numexpr=2.8.7=py39h286c3b5_0
  - numpy=1.21.6=py39hac523dd_1
  - numpy-base=1.21.6=py39h375b286_1
  - openjpeg=2.5.2=he7f1fd0_0
  - openssl=3.4.0=hb9d3cd8_0
  - packaging=24.2=pyhd8ed1ab_2
  - pandas=2.0.3=py39h1128e8f_0
  - parso=0.8.4=pyhd8ed1ab_1
  - pcre2=10.43=hcad00b1_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=10.3.0=py39h90c7501_0
  - pip=24.2=py39h06a4308_0
  - pixman=0.44.2=h29eaf8c_0
  - platformdirs=4.3.6=pyhd8ed1ab_1
  - pluggy=1.5.0=py39h06a4308_0
  - ply=3.11=py39h06a4308_0
  - prompt-toolkit=3.0.48=pyha770c72_1
  - psutil=6.1.1=py39h8cd3c5a_0
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pulseaudio-client=17.0=hb77b528_0
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pygments=2.18.0=pyhd8ed1ab_1
  - pyparsing=3.0.9=py39h06a4308_0
  - pyqt=5.15.10=py39h6a678d5_0
  - pyqt5-sip=12.13.0=py39h5eee18b_0
  - pytest=8.3.4=py39h06a4308_0
  - python=3.9.21=he870216_1
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - python_abi=3.9=2_cp39
  - pytz=2024.1=py39h06a4308_0
  - pyzmq=26.2.0=py39h4e4fb57_3
  - qt-main=5.15.8=hc9dc06e_21
  - readline=8.2=h5eee18b_0
  - scipy=1.11.4=py39heeff2f4_0
  - setuptools=75.1.0=py39h06a4308_0
  - sip=6.7.12=py39h6a678d5_0
  - six=1.17.0=pyhd8ed1ab_0
  - sqlite=3.45.3=h5eee18b_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.14=h39e8969_0
  - tomli=2.0.1=py39h06a4308_0
  - tornado=6.4.2=py39h8cd3c5a_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - trimesh=4.6.4=pyh7b2049a_0
  - typing_extensions=4.12.2=pyha770c72_1
  - tzdata=2024b=h04d1e81_0
  - unicodedata2=15.1.0=py39h5eee18b_0
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - wheel=0.44.0=py39h06a4308_0
  - xcb-util=0.4.0=hd590300_1
  - xcb-util-image=0.4.0=h8ee46fc_1
  - xcb-util-keysyms=0.4.0=h8ee46fc_1
  - xcb-util-renderutil=0.3.9=hd590300_1
  - xcb-util-wm=0.4.1=h8ee46fc_1
  - xkeyboard-config=2.42=h4ab18f5_0
  - xorg-kbproto=1.0.7=hb9d3cd8_1003
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.5=he73a12e_0
  - xorg-libx11=1.8.9=h8ee46fc_0
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxrender=0.9.11=hd590300_0
  - xorg-renderproto=0.11.1=hb9d3cd8_1003
  - xorg-xextproto=7.3.0=hb9d3cd8_1004
  - xorg-xf86vidmodeproto=2.3.1=hb9d3cd8_1005
  - xorg-xproto=7.0.31=h27cfd23_1007
  - xz=5.4.6=h5eee18b_1
  - zeromq=4.3.5=h3b0a872_7
  - zipp=3.21.0=pyhd8ed1ab_1
  - zlib=1.2.13=h4ab18f5_6
  - zstd=1.5.6=hc292b87_0
