name: LCC
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - blas=1.0=mkl
  - ca-certificates=2026.2.25=hbd8a1cb_0
  - certifi=2025.8.3=pyhd8ed1ab_0
  - cython=0.29.24=py39he80948d_0
  - exceptiongroup=1.2.0=py39h06a4308_0
  - freetype=2.10.4=h0708190_1
  - giflib=5.2.1=h36c2ea0_2
  - imageio=2.37.0=pyhfb79c49_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - iniconfig=2.1.0=py39h06a4308_0
  - intel-openmp=2021.3.0=h06a4308_3350
  - jbig=2.1=h7f98852_2003
  - jpeg=9d=h36c2ea0_0
  - lazy-loader=0.4=pyhd8ed1ab_2
  - lazy_loader=0.4=pyhd8ed1ab_2
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.35.1=h7274673_9
  - lerc=2.2.1=h9c3ff4c_0
  - libblas=3.9.0=11_linux64_mkl
  - libcblas=3.9.0=11_linux64_mkl
  - libdeflate=1.7=h7f98852_5
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgfortran-ng=13.2.0=h69a702a_0
  - libgfortran5=13.2.0=ha4646dd_0
  - libgomp=9.3.0=h5101ec6_17
  - liblapack=3.9.0=11_linux64_mkl
  - libpng=1.6.37=h21135ba_2
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - libtiff=4.3.0=hf544144_1
  - libwebp=1.2.0=h3452ae3_0
  - libwebp-base=1.2.0=h7f98852_2
  - lz4-c=1.9.3=h9c3ff4c_1
  - mkl=2021.3.0=h06a4308_520
  - mkl-service=2.4.0=py39h7f8727e_0
  - mkl_fft=1.3.0=py39h42c9631_2
  - mkl_random=1.2.2=py39h51133e4_0
  - ncurses=6.2=he6710b0_1
  - openssl=1.1.1w=h7f8727e_0
  - packaging=25.0=py39h06a4308_0
  - pillow=9.0.1=py39h22f2fdc_0
  - pluggy=1.5.0=py39h06a4308_0
  - pygments=2.19.1=py39h06a4308_0
  - pytest=8.4.1=py39h06a4308_0
  - python=3.9.6=h12debd9_1
  - python_abi=3.9=2_cp39
  - readline=8.1=h27cfd23_0
  - six=1.16.0=pyhd3eb1b0_0
  - sqlite=3.36.0=hc218d9a_0
  - tk=8.6.10=hbc83047_0
  - tomli=2.2.1=py39h06a4308_0
  - trimesh=4.7.4=pyh7b2049a_0
  - tzdata=2021a=h5d7bf9c_0
  - wheel=0.45.1=py39h06a4308_0
  - xz=5.2.5=h7b6447c_0
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.5.0=ha95c52a_0
  - pip:
      - llvmlite==0.40.1
      - numba==0.57.1
      - numpy==1.23.5
      - pip==24.3.1
      - scipy==1.10.1
      - setuptools==80.9.0
prefix: /project/sjpo228_uksr/AhmedHYassin/isthmus_env_gpu
