name: marching_cubes
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - aom=3.8.2=h59595ed_0
  - blas=1.0=openblas
  - blosc=1.21.5=h0f2a231_0
  - bottleneck=1.3.7=py312ha883a20_0
  - brotli=1.1.0=hd590300_1
  - brotli-bin=1.1.0=hd590300_1
  - brunsli=0.1=h9c3ff4c_0
  - bzip2=1.0.8=hd590300_5
  - c-blosc2=2.13.2=hb4ffafa_0
  - ca-certificates=2024.9.24=h06a4308_0
  - charls=2.4.2=h59595ed_0
  - cython=3.0.0=py312h5eee18b_0
  - dav1d=1.2.1=hd590300_0
  - freetype=2.12.1=h267a509_2
  - giflib=5.2.1=h0b41bf4_3
  - imagecodecs=2024.1.1=py312h55207c9_2
  - imageio=2.34.0=pyh4b66e23_0
  - jxrlib=1.1=hd590300_3
  - lazy_loader=0.3=pyhd8ed1ab_0
  - lcms2=2.16=hb7c19ff_0
  - ld_impl_linux-64=2.40=h41732ed_0
  - lerc=4.0.0=h27087fc_0
  - libaec=1.1.2=h59595ed_1
  - libavif16=1.0.4=hd9d6309_2
  - libblas=3.9.0=21_linux64_openblas
  - libbrotlicommon=1.1.0=hd590300_1
  - libbrotlidec=1.1.0=hd590300_1
  - libbrotlienc=1.1.0=hd590300_1
  - libcblas=3.9.0=21_linux64_openblas
  - libdeflate=1.19=hd590300_0
  - libexpat=2.6.2=h59595ed_0
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=13.2.0=h807b86a_5
  - libgfortran-ng=13.2.0=h69a702a_5
  - libgfortran5=13.2.0=ha4646dd_5
  - libgomp=13.2.0=h807b86a_5
  - libhwy=1.0.7=h00ab1b0_0
  - libjpeg-turbo=3.0.0=hd590300_1
  - libjxl=0.10.1=h5b01ea3_0
  - liblapack=3.9.0=21_linux64_openblas
  - libnsl=2.0.1=hd590300_0
  - libopenblas=0.3.26=pthreads_h413a1c8_0
  - libpng=1.6.43=h2797004_0
  - libspatialindex=2.0.0=he02047a_0
  - libsqlite=3.45.2=h2797004_0
  - libstdcxx-ng=13.2.0=h7e041cc_5
  - libtiff=4.6.0=ha9c0a0a_2
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp-base=1.3.2=hd590300_0
  - libxcb=1.15=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.2.13=hd590300_5
  - libzopfli=1.0.3=h9c3ff4c_0
  - lz4-c=1.9.4=hcb278e6_0
  - ncurses=6.4=h59595ed_2
  - networkx=3.2.1=pyhd8ed1ab_0
  - numexpr=2.8.7=py312he7dcb8a_0
  - numpy=1.26.4=py312heda63a1_0
  - openjpeg=2.5.2=h488ebb8_0
  - openssl=3.2.1=hd590300_0
  - packaging=24.0=pyhd8ed1ab_0
  - pandas=2.1.1=py312h526ad5a_0
  - pillow=10.2.0=py312hf3581a9_0
  - pip=24.0=pyhd8ed1ab_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - python=3.12.2=hab00c5b_0_cpython
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - python_abi=3.12=4_cp312
  - pytz=2023.3.post1=py312h06a4308_0
  - pywavelets=1.4.1=py312hc7c0aa3_1
  - rav1e=0.6.6=he8a937b_2
  - readline=8.2=h8228510_1
  - rtree=1.3.0=py312h18067a2_2
  - scikit-image=0.22.0=py312hfb8ada1_2
  - scipy=1.14.1=py312h2809609_0
  - setuptools=69.2.0=pyhd8ed1ab_0
  - six=1.16.0=pyhd3eb1b0_1
  - snappy=1.1.10=h9fff704_0
  - svt-av1=2.0.0=h59595ed_0
  - tifffile=2024.2.12=pyhd8ed1ab_0
  - tk=8.6.13=noxft_h4845f30_101
  - trimesh=4.2.0=pyhd8ed1ab_0
  - tzdata=2024a=h0c530f3_0
  - wheel=0.42.0=pyhd8ed1ab_0
  - xorg-libxau=1.0.11=hd590300_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xz=5.2.6=h166bdaf_0
  - zfp=1.0.1=h59595ed_0
  - zlib-ng=2.0.7=h0b41bf4_0
  - zstd=1.5.5=hfc55251_0
prefix: /home/vbmo224/.conda/envs/marching_cubes
